<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AlumnosGeneralesSeeder extends Seeder
{
    public function run()
    {
        DB::table('alumnos_generales')->insert([
            [
                'no_de_control' => 'A123456789',
                'lugar_nacimiento' => 'Ciudad de México',
                'domicilio_calle' => 'Av. Reforma 123',
                'domicilio_colonia' => 'Centro',
                'ciudad' => 'Ciudad de México',
                'entidad_federativa' => 'Ciudad de México',
                'codigo_postal' => 06600,
                'telefono' => '555-123-4567',
                'nombre_padre' => 'Juan Pérez',
                'ocupacion_padre' => 'Ingeniero',
                'domicilio_calle_padre' => 'Calle Hidalgo 456',
                'domicilio_colonia_padre' => 'Chapultepec',
                'domicilio_ciudad_padre' => 'Ciudad de México',
                'domicilio_entidad_fed_padre' => 'Ciudad de México',
                'domicilio_telefono_padre' => '555-765-4321',
                'nombre_madre' => 'María López',
                'ocupacion_madre' => 'Médico',
                'domicilio_calle_madre' => 'Calle Insurgentes 789',
                'domicilio_colonia_madre' => 'Roma Norte',
                'domicilio_ciudad_madre' => 'Ciudad de México',
                'domicilio_entidad_fed_madre' => 'Ciudad de México',
                'domicilio_telefono_madre' => '555-987-6543',
                'nombre_empresa' => 'Empresa X',
                'cargo_desempenado' => 'Gerente',
                'ingreso_mensual' => 45000.00,
                'turno' => 1,
                'antiguedad' => '5 años',
                'nombre_jefe' => 'Carlos Torres',
                'domicilio_calle_empresa' => 'Av. Juárez 101',
                'domicilio_colonia_empresa' => 'Centro',
                'domicilio_ciudad_empresa' => 'Ciudad de México',
                'domicilio_entidad_fed_empresa' => 'Ciudad de México',
                'domicilio_telefono_empresa' => '555-333-2222',
                'nombre_esposa' => 'Ana García',
                'ocupacion_esposa' => 'Abogada',
                'no_dependientes' => 2,
                'comunidad_indigena' => null,
                'lengua_indigena' => null,
                'municipio_nac' => 'Gustavo A. Madero',
                'municipio_dom' => 'Benito Juárez',
                'domicilio_calle_tutor' => null,
                'nombre_tutor' => null,
                'domicilio_ciudad_tutor' => null,
                'domicilio_colonia_tutor' => null,
                'domicilio_telefono_tutor' => null,
                'domicilio_entidad_federativa_titular' => null,
                'clave_preparatoria' => 'PREPA-123',
                'municipio' => 'Benito Juárez',
                'entidad_federativa_prepa' => 'Ciudad de México',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_de_control' => 'B987654321',
                'lugar_nacimiento' => 'Guadalajara',
                'domicilio_calle' => 'Calle Hidalgo 456',
                'domicilio_colonia' => 'Chapultepec',
                'ciudad' => 'Guadalajara',
                'entidad_federativa' => 'Jalisco',
                'codigo_postal' => 44100,
                'telefono' => '333-123-4567',
                'nombre_padre' => 'Luis Gómez',
                'ocupacion_padre' => 'Contador',
                'domicilio_calle_padre' => 'Av. Vallarta 789',
                'domicilio_colonia_padre' => 'Centro',
                'domicilio_ciudad_padre' => 'Guadalajara',
                'domicilio_entidad_fed_padre' => 'Jalisco',
                'domicilio_telefono_padre' => '333-987-6543',
                'nombre_madre' => 'Carmen Torres',
                'ocupacion_madre' => 'Docente',
                'domicilio_calle_madre' => 'Calle Juárez 123',
                'domicilio_colonia_madre' => 'Zapopan',
                'domicilio_ciudad_madre' => 'Guadalajara',
                'domicilio_entidad_fed_madre' => 'Jalisco',
                'domicilio_telefono_madre' => '333-765-4321',
                'nombre_empresa' => 'Empresa Y',
                'cargo_desempenado' => 'Analista',
                'ingreso_mensual' => 30000.00,
                'turno' => 2,
                'antiguedad' => '3 años',
                'nombre_jefe' => 'Laura Martínez',
                'domicilio_calle_empresa' => 'Calle Morelos 456',
                'domicilio_colonia_empresa' => 'Zapopan',
                'domicilio_ciudad_empresa' => 'Guadalajara',
                'domicilio_entidad_fed_empresa' => 'Jalisco',
                'domicilio_telefono_empresa' => '333-333-4444',
                'nombre_esposa' => 'Carolina Pérez',
                'ocupacion_esposa' => 'Ingeniera',
                'no_dependientes' => 3,
                'comunidad_indigena' => null,
                'lengua_indigena' => null,
                'municipio_nac' => 'Zapopan',
                'municipio_dom' => 'Guadalajara',
                'domicilio_calle_tutor' => null,
                'nombre_tutor' => null,
                'domicilio_ciudad_tutor' => null,
                'domicilio_colonia_tutor' => null,
                'domicilio_telefono_tutor' => null,
                'domicilio_entidad_federativa_titular' => null,
                'clave_preparatoria' => 'PREPA-456',
                'municipio' => 'Guadalajara',
                'entidad_federativa_prepa' => 'Jalisco',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
