<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AlumnosSeeder extends Seeder
{
    public function run()
    {
        DB::table('alumnos')->insert([
            [
                'no_de_control' => 'A123456789',
                'carrera' => 'INF',
                'reticula' => 2020,
                'especialidad' => 'SINF',
                'nivel_escolar' => 'L',
                'semestre' => 6,
                'clave_interna' => 'ABC123',
                'estatus_alumno' => 'ACT',
                'plan_de_estudios' => 'A',
                'apellido_paterno' => 'García',
                'apellido_materno' => 'Hernández',
                'nombre_alumno' => 'Luis Fernando',
                'curp_alumno' => 'GARL900101HDFRNS09',
                'fecha_nacimiento' => '1990-01-01',
                'sexo' => 'M',
                'estado_civil' => 'S',
                'tipo_ingreso' => 1,
                'periodo_ingreso_it' => '2020A',
                'ultimo_periodo_inscrito' => '2023B',
                'promedio_periodo_anterior' => 9.5,
                'promedio_aritmetico_acumulado' => 9.2,
                'creditos_aprobados' => 150,
                'creditos_cursados' => 180,
                'promedio_final_alcanzado' => 9.3,
                'tipo_servicio_medico' => 'M',
                'clave_servicio_medico' => 'IMSS123456',
                'escuela_procedencia' => 'Preparatoria Benito Juárez',
                'tipo_escuela' => 1,
                'domicilio_escuela' => 'Av. Juárez 123',
                'entidad_procedencia' => 'Ciudad de México',
                'ciudad_procedencia' => 'Ciudad de México',
                'correo_electronico' => 'luis.garcia@example.com',
                'periodos_revalidacion' => 0,
                'indice_reprobacion_acumulado' => 0.000001,
                'becado_por' => 'Gobierno Federal',
                'nip' => 1234,
                'tipo_alumno' => 'A',
                'nacionalidad' => 'MEX',
                'usuario' => 'admin',
                'fecha_actualizacion' => now(),
                'folio' => 12345,
                'fecha_titulacion' => null,
                'opcion_titulacion' => null,
                'estatus_alumno_fecha' => now(),
                'estatus_alumno_usuario' => 'admin',
                'estatus_alumno_anterior' => null,
                'periodo_titulacion' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_de_control' => 'B987654321',
                'carrera' => 'ADM',
                'reticula' => 2018,
                'especialidad' => 'MKT',
                'nivel_escolar' => 'L',
                'semestre' => 8,
                'clave_interna' => 'DEF456',
                'estatus_alumno' => 'ACT',
                'plan_de_estudios' => 'B',
                'apellido_paterno' => 'López',
                'apellido_materno' => 'Martínez',
                'nombre_alumno' => 'Ana Sofía',
                'curp_alumno' => 'LOMA950201MDFRNS05',
                'fecha_nacimiento' => '1995-02-01',
                'sexo' => 'F',
                'estado_civil' => 'S',
                'tipo_ingreso' => 1,
                'periodo_ingreso_it' => '2018A',
                'ultimo_periodo_inscrito' => '2023A',
                'promedio_periodo_anterior' => 8.7,
                'promedio_aritmetico_acumulado' => 8.9,
                'creditos_aprobados' => 180,
                'creditos_cursados' => 180,
                'promedio_final_alcanzado' => 9.0,
                'tipo_servicio_medico' => 'S',
                'clave_servicio_medico' => 'ISSSTE789012',
                'escuela_procedencia' => 'Preparatoria Sor Juana',
                'tipo_escuela' => 2,
                'domicilio_escuela' => 'Calle Hidalgo 456',
                'entidad_procedencia' => 'Jalisco',
                'ciudad_procedencia' => 'Guadalajara',
                'correo_electronico' => 'ana.lopez@example.com',
                'periodos_revalidacion' => 0,
                'indice_reprobacion_acumulado' => 0.000000,
                'becado_por' => 'Beca Universitaria',
                'nip' => 5678,
                'tipo_alumno' => 'B',
                'nacionalidad' => 'MEX',
                'usuario' => 'admin',
                'fecha_actualizacion' => now(),
                'folio' => 67890,
                'fecha_titulacion' => null,
                'opcion_titulacion' => null,
                'estatus_alumno_fecha' => now(),
                'estatus_alumno_usuario' => 'admin',
                'estatus_alumno_anterior' => null,
                'periodo_titulacion' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
