<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PersonalsSeeder extends Seeder
{
    public function run()
    {
        DB::table('personals')->insert([
            [
                'rfc' => 'ABCD123456EFG',
                'clave_centro_seit' => 'CT001',
                'clave_area' => 'ADM001',
                'curp_empleado' => 'ABCD890123HDFRLL09',
                'no_tarjeta' => 12345,
                'apellidos_empleado' => 'López Pérez',
                'nombre_empleado' => 'Juan Carlos',
                'horas_nombramiento' => 40,
                'nombramiento' => 'A',
                'clases' => 'S',
                'ingreso_rama' => '2020',
                'inicio_gobierno' => '2018',
                'inicio_sep' => '2019',
                'inicio_plantel' => '2020',
                'domicilio_empleado' => 'Calle Reforma',
                'colonia_empleado' => 'Centro',
                'codigo_postal_empleado' => 06600,
                'localidad' => 'Ciudad de México',
                'telefono_empleado' => '555-123-4567',
                'sexo_empleado' => 'M',
                'estado_civil' => 'Soltero',
                'fecha_nacimiento' => '1989-02-15',
                'lugar_nacimiento' => 9,
                'institucion_egreso' => 'UNAM',
                'nivel_estudios' => 'L',
                'grado_maximo_estudios' => 'T',
                'estudios' => 'Ingeniería en Computación',
                'fecha_titulacion' => '2013-06-15',
                'cedula_profesional' => '1234567',
                'especializacion' => 'Sistemas Distribuidos',
                'idiomas_domina' => 'Español, Inglés',
                'status_empleado' => 'A1',
                'correo_electronico' => 'juan.lopez@example.com',
                'padre' => 'José López',
                'madre' => 'María Pérez',
                'conyuge' => 'Maria Alonso',
                'hijos' => 0,
                'titulo_num' => '00123',
                'titulo_num_libro' => '456',
                'titulo_num_foja' => 12,
                'titulo_num_anio' => 2013,
                'num_cartilla_smn' => 'SMN00123',
                'anio_clase' => 2010,
                'pigmentacion' => 'Blanca',
                'pelo' => 'Negro',
                'frente' => 'Amplia',
                'cejas' => 'Pobladas',
                'ojos' => 'Cafés',
                'nariz' => 'Recta',
                'boca' => 'Mediana',
                'estaturamts' => 175,
                'pesokg' => 70,
                'senas_visibles' => 'Lunar en la mejilla derecha',
                'pais' => 'México',
                'pasport' => 123456,
                'fm' => 'abc',
                'entrada_salida' => 'N',
                'observaciones_empleado' => 'Empleado activo desde 2020',
                'area_academica' => 'INF',
                'tipo_personal' => 'A',
                'tipo_control' => 'F',
                'emergencia' => 'Contacto: María Pérez, Teléfono: 555-987-6543',
                'entidad_federativa' => 'Ciudad de México',
                'municipio_empleado' => 'Benito Juárez',
                'nacionalidad' => 'Mexicano',
                'acta_nacimiento_numero' => 12345,
                'acta_nacimiento_foja' => 12,
                'acta_nacimiento_libro' => '789',
                'acta_nacimiento_anio' => 1989,
                'pasaporte_vigencia_inicio' => '2013-06-15',
                'pasaporte_vigencia_fin' => '2013-06-15',
                'pasaporte_puesto_autorizado' => '2013-06-15',
                'otros_dependientes' => 0,
                'instituto_titulacion' => 'UNAM',
                'anio_inicio_estudios' => 2008,
                'anio_termino_estudios' => 2013,
                'domicilio_empleado_numero' => '123',
                'fecha_cedula' => '2013-06-20',
                'institucion_expide_titulo' => 'UNAM',
                'institucion_expide_cedula' => 'UNAM',
                'inactivo_rc' => 'N',
                'documento_obtenido' => 'Título Profesional',
                'documento_obtenido_fecha' => '2013-06-15',
                'documento_obtenido_institucion' => 'UNAM',
                'apellido_paterno' => 'López',
                'apellido_materno' => 'Pérez',
                'tit_abreviado' => 'Ing.',
                'estudios1' => 'Diplomado en Seguridad Informática',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Agregar más registros según sea necesario
        ]);
    }
}
